// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwPYXUH0eEXKXI_g0CAuYc56Qq68HApZs',
    appId: '1:82796004884:web:4b32671a59518e07c14901',
    messagingSenderId: '82796004884',
    projectId: 'flutterauth-98f8f',
    authDomain: 'flutterauth-98f8f.firebaseapp.com',
    storageBucket: 'flutterauth-98f8f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXf-dUo6t-xNI7dLgsAHkjT2ydC5gQWVk',
    appId: '1:82796004884:android:f3a7eba6c3c08c34c14901',
    messagingSenderId: '82796004884',
    projectId: 'flutterauth-98f8f',
    storageBucket: 'flutterauth-98f8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2eoo_soz6JHaBfYhDLrBxEGY9YV4-2Jk',
    appId: '1:82796004884:ios:95378cd0e7b69c22c14901',
    messagingSenderId: '82796004884',
    projectId: 'flutterauth-98f8f',
    storageBucket: 'flutterauth-98f8f.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2eoo_soz6JHaBfYhDLrBxEGY9YV4-2Jk',
    appId: '1:82796004884:ios:83ea3cb9eb3da2c5c14901',
    messagingSenderId: '82796004884',
    projectId: 'flutterauth-98f8f',
    storageBucket: 'flutterauth-98f8f.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
